from email.utils import make_msgid
import smtplib, ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import datetime

def ledEmail_function(): # Sending low light intensity email
  sender_email = "senderemail@email"
  receiver_email = "receiveremail@email"
  password = "password"

  message_id = make_msgid(domain='example.com')

  message = MIMEMultipart("alternative")
  message["Subject"] = "ATTENTION: IoT Smarthub LED"
  message["From"] = sender_email
  message["To"] = receiver_email
  message['Message-ID'] = message_id

  now = datetime.datetime.now()
  current_time = now.strftime("%H:%M:%S")

  # Message text
  text = f"""\
  Salutations,
  This is a autogenerated email from the IoT Smarthub app.
  We've detected that the light intensity is less than your desired threshold.
  The light has been turned ON at {current_time}.


  Thank you,

  Your SmartHub :)"""

  html = f"""\
  <html>
    <body>
      <p>Salutations,<br>
        This is a autogenerated email from the IoT Smarthub app.
        We've detected that the light intensity is less than your desired threshold.
        The light has been turned ON at {current_time}.


        Thank you,

        Your SmartHub :)<br>
      </p>
    </body>
  </html>
  """

  part1 = MIMEText(text, "plain")
  part2 = MIMEText(html, "html")

  message.attach(part1)
  message.attach(part2)

  context = ssl.create_default_context()
  with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
      server.login(sender_email, password)
      server.sendmail(
          sender_email, receiver_email, message.as_string()
      )

ledEmail_function()